package server

import (
	"errors"
	"fmt"
	"strings"
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

const initialAdminPasswordCredential = "initial-admin-password"

// CreateBootstrapAdmin creates the fixed first administrator once. When the
// password was generated by TokenHub, its retrievable copy is encrypted in the
// same transaction so a crash cannot leave an unreachable account behind.
func (s *GormStore) CreateBootstrapAdmin(user AdminUser, password string, retainInitialPassword bool) (AdminUser, bool, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	var created AdminUser
	createdNow := false
	err := s.db.Transaction(func(tx *gorm.DB) error {
		var count int64
		if err := tx.Model(&AdminUser{}).
			Where("id = ? OR username = ? OR email = ?", user.ID, user.Username, user.Email).
			Count(&count).Error; err != nil {
			return err
		}
		if count > 0 {
			return nil
		}
		if err := lockUserTeamsForMutation(tx, user.TeamID, user.TeamIDs); err != nil {
			return err
		}
		var err error
		created, err = createAdminUser(tx, user, password)
		if err != nil {
			return err
		}
		if retainInitialPassword {
			ciphertext := s.encryptSecret(password)
			if !strings.HasPrefix(ciphertext, "enc:v1:") {
				return fmt.Errorf("encrypt generated initial admin password")
			}
			credential := BootstrapCredential{
				Name:       initialAdminPasswordCredential,
				Ciphertext: ciphertext,
				CreatedAt:  time.Now().UTC(),
			}
			if err := tx.Clauses(clause.OnConflict{
				Columns:   []clause.Column{{Name: "name"}},
				DoUpdates: clause.AssignmentColumns([]string{"ciphertext", "created_at"}),
			}).Create(&credential).Error; err != nil {
				return err
			}
		}
		createdNow = true
		return nil
	})
	if err != nil && AsHTTPError(err).Code == "admin_user_conflict" {
		return AdminUser{}, false, nil
	}
	return created, createdNow, err
}

// InitialAdminPassword decrypts the generated first-run password for the local
// administrative CLI. It disappears after the first successful login or any
// password reset.
func (s *GormStore) InitialAdminPassword() (string, bool, error) {
	var credential BootstrapCredential
	if err := s.db.First(&credential, "name = ?", initialAdminPasswordCredential).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return "", false, nil
		}
		return "", false, err
	}
	password := s.decryptSecret(credential.Ciphertext)
	if strings.TrimSpace(password) == "" {
		return "", true, fmt.Errorf("decrypt generated initial admin password")
	}
	return password, true, nil
}

func deleteInitialAdminPassword(db *gorm.DB, userID string) error {
	if userID != "usr_admin" {
		return nil
	}
	return db.Delete(&BootstrapCredential{}, "name = ?", initialAdminPasswordCredential).Error
}
