// Command pluginmanifestgen mirrors the production YAML types into the standalone DevKit.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	root := flag.String("root", ".", "Repository root")
	check := flag.Bool("check", false, "Check that the generated schema is current")
	flag.Parse()
	if err := generate(*root, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(root string, check bool) error {
	fs := token.NewFileSet()
	entries, err := os.ReadDir(filepath.Join(root, "backend/internal/plugin"))
	if err != nil {
		return err
	}
	types := map[string]*ast.TypeSpec{}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fs, filepath.Join(root, "backend/internal/plugin", entry.Name()), nil, 0)
		if err != nil {
			return err
		}

		for _, decl := range file.Decls {
			generic, ok := decl.(*ast.GenDecl)
			if !ok || generic.Tok != token.TYPE {
				continue
			}
			for _, spec := range generic.Specs {
				typ := spec.(*ast.TypeSpec)
				types[typ.Name.Name] = typ
			}
		}
	}
	selected := map[string]bool{}
	imports := map[string]bool{}
	var visit func(string)
	visit = func(name string) {
		typ := types[name]
		if typ == nil || selected[name] {
			return
		}
		selected[name] = true
		var inspect func(ast.Expr)
		inspect = func(expr ast.Expr) {
			switch expr := expr.(type) {
			case *ast.Ident:
				visit(expr.Name)
			case *ast.StarExpr:
				inspect(expr.X)
			case *ast.ArrayType:
				inspect(expr.Elt)
			case *ast.MapType:
				inspect(expr.Key)
				inspect(expr.Value)
			case *ast.StructType:
				for _, field := range expr.Fields.List {
					inspect(field.Type)
				}
			case *ast.SelectorExpr:
				if pkg, ok := expr.X.(*ast.Ident); ok {
					imports[pkg.Name] = true
				}
			}
		}
		inspect(typ.Type)
	}
	visit("Manifest")
	names := make([]string, 0, len(selected))
	for name := range selected {
		names = append(names, name)
	}
	sort.Strings(names)
	var output bytes.Buffer
	output.WriteString("// Code generated by backend/cmd/pluginmanifestgen; DO NOT EDIT.\npackage main\n\n")
	for _, pkg := range []string{"json", "time"} {
		if imports[pkg] {
			path := pkg
			if pkg == "json" {
				path = "encoding/json"
			}
			fmt.Fprintf(&output, "import %q\n", path)
		}
	}
	for _, name := range names {
		fmt.Fprintf(&output, "\ntype %s ", name)
		if _, ok := types[name].Type.(*ast.Ident); ok {
			output.WriteString("= ")
		}
		if err := format.Node(&output, fs, types[name].Type); err != nil {
			return err
		}
		output.WriteByte('\n')
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return err
	}
	path := filepath.Join(root, "plugin-devkit/cmd/tokenhub-plugin-test/manifest_generated.go")
	if check {
		existing, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !bytes.Equal(existing, formatted) {
			return fmt.Errorf("DevKit schema is stale; run go run ./backend/cmd/pluginmanifestgen -root . from the repository root")
		}
		return nil
	}
	return os.WriteFile(path, formatted, 0644)
}
