// Code generated by backend/cmd/pluginmanifestgen; DO NOT EDIT.
package main

type ActionKind = string

type ActionManifest struct {
	ID           string            `yaml:"id"`
	Kind         ActionKind        `yaml:"kind"`
	Title        string            `yaml:"title"`
	Capability   string            `yaml:"capability"`
	Subject      string            `yaml:"subject"`
	Metadata     map[string]string `yaml:"metadata"`
	InputSchema  map[string]any    `yaml:"input_schema"`
	OutputSchema map[string]any    `yaml:"output_schema"`
}

type BackgroundJobManifest struct {
	ID             string                   `yaml:"id"`
	Title          string                   `yaml:"title"`
	Capability     string                   `yaml:"capability"`
	Subject        string                   `yaml:"subject"`
	Schedule       string                   `yaml:"schedule"`
	TimeoutMillis  int                      `yaml:"timeout_millis"`
	MaxConcurrency int                      `yaml:"max_concurrency"`
	Retry          BackgroundJobRetryPolicy `yaml:"retry"`
	InputSchema    map[string]any           `yaml:"input_schema"`
	OutputSchema   map[string]any           `yaml:"output_schema"`
}

type BackgroundJobRetryPolicy struct {
	MaxAttempts       int     `json:"max_attempts,omitempty" yaml:"max_attempts"`
	BackoffMillis     int     `json:"backoff_millis,omitempty" yaml:"backoff_millis"`
	BackoffMultiplier float64 `json:"backoff_multiplier,omitempty" yaml:"backoff_multiplier"`
	JitterMillis      int     `json:"jitter_millis,omitempty" yaml:"jitter_millis"`
	DeadLetter        bool    `json:"dead_letter,omitempty" yaml:"dead_letter"`
}

type Category = string

type GatewayDataClass = string

type GatewayHookFailurePolicy = string

type GatewayHookManifest struct {
	ID            string                   `yaml:"id"`
	Stage         GatewayHookStage         `yaml:"stage"`
	Priority      int                      `yaml:"priority"`
	Before        []string                 `yaml:"before"`
	After         []string                 `yaml:"after"`
	Subject       string                   `yaml:"subject"`
	Metadata      map[string]string        `yaml:"metadata"`
	Scope         GatewayHookScope         `yaml:"scope"`
	Reads         []GatewayDataClass       `yaml:"reads"`
	Writes        []GatewayDataClass       `yaml:"writes"`
	FailurePolicy GatewayHookFailurePolicy `yaml:"failure_policy"`
	TimeoutMillis int                      `yaml:"timeout_millis"`
}

type GatewayHookScope struct {
	ProjectIDs     []string `json:"project_ids,omitempty" yaml:"project_ids"`
	APIKeyIDs      []string `json:"api_key_ids,omitempty" yaml:"api_key_ids"`
	ProviderTypes  []string `json:"provider_types,omitempty" yaml:"provider_types"`
	ProviderIDs    []string `json:"provider_ids,omitempty" yaml:"provider_ids"`
	ResourceIDs    []string `json:"resource_ids,omitempty" yaml:"resource_ids"`
	ResourceTypes  []string `json:"resource_types,omitempty" yaml:"resource_types"`
	RouteProtocols []string `json:"route_protocols,omitempty" yaml:"route_protocols"`
	Operations     []string `json:"operations,omitempty" yaml:"operations"`
}

type GatewayHookStage = string

type Kind = string

type Manifest struct {
	SchemaVersion int                   `yaml:"schema_version"`
	ID            string                `yaml:"id"`
	Name          string                `yaml:"name"`
	Version       string                `yaml:"version"`
	Summary       string                `yaml:"summary"`
	Description   string                `yaml:"description"`
	Category      Category              `yaml:"category"`
	HostAdapter   string                `yaml:"host_adapter"`
	Dependencies  []ManifestDependency  `yaml:"dependencies"`
	Settings      ManifestSettings      `yaml:"settings"`
	TokenHub      ManifestCompatibility `yaml:"tokenhub"`
	Distribution  ManifestDistribution  `yaml:"distribution"`
	Marketplace   *MarketplaceMetadata  `yaml:"marketplace"`
	Kinds         []Kind                `yaml:"kinds"`
	Placement     []Placement           `yaml:"placement"`
	Entry         ManifestEntry         `yaml:"entry"`
	Capabilities  ManifestCapabilities  `yaml:"capabilities"`
	Permissions   ManifestPermissions   `yaml:"permissions"`
}

type ManifestBackendEntry struct {
	Command  string `yaml:"command"`
	Protocol string `yaml:"protocol"`
}

type ManifestCapabilities struct {
	ProviderTypes []string                       `yaml:"provider_types"`
	ResourceTypes []ManifestProviderResourceType `yaml:"provider_resource_types"`
	Provider      ManifestProvider               `yaml:"provider"`
	SIM           ManifestSIM                    `yaml:"sim"`
	Gateway       []string                       `yaml:"gateway"`
	AdminUI       []string                       `yaml:"admin_ui"`
	Hooks         []GatewayHookManifest          `yaml:"hooks"`
	Actions       []ActionManifest               `yaml:"actions"`
	Background    []BackgroundJobManifest        `yaml:"background_jobs"`
}

type ManifestCompatibility struct {
	PluginAPI string `yaml:"plugin_api"`
	MinCore   string `yaml:"min_core"`
	MaxCore   string `yaml:"max_core"`
}

type ManifestDataPermissions struct {
	Read  []GatewayDataClass `yaml:"read"`
	Write []GatewayDataClass `yaml:"write"`
}

type ManifestDependency struct {
	ID      string `json:"id" yaml:"id"`
	Version string `json:"version,omitempty" yaml:"version"`
}

type ManifestDistribution struct {
	MarketplaceURL     string `json:"marketplace_url,omitempty" yaml:"marketplace_url"`
	RepositoryURL      string `json:"repository_url,omitempty" yaml:"repository_url"`
	DownloadURL        string `json:"download_url,omitempty" yaml:"download_url"`
	ChecksumSHA256     string `json:"checksum_sha256,omitempty" yaml:"checksum_sha256"`
	SignatureURL       string `json:"signature_url,omitempty" yaml:"signature_url"`
	SignatureAlgorithm string `json:"signature_algorithm,omitempty" yaml:"signature_algorithm"`
	SignatureKeyID     string `json:"signature_key_id,omitempty" yaml:"signature_key_id"`
	HomepageURL        string `json:"homepage_url,omitempty" yaml:"homepage_url"`
	License            string `json:"license,omitempty" yaml:"license"`
}

type ManifestEntry struct {
	Backend  *ManifestBackendEntry  `yaml:"backend"`
	Frontend *ManifestFrontendEntry `yaml:"frontend"`
}

type ManifestFrontendEntry struct {
	Schema string `yaml:"schema"`
}

type ManifestModelCategory struct {
	Key               string   `json:"key" yaml:"key"`
	Label             string   `json:"label,omitempty" yaml:"label"`
	Order             int      `json:"order,omitempty" yaml:"order"`
	Aliases           []string `json:"aliases,omitempty" yaml:"aliases"`
	FamilyPrefixes    []string `json:"family_prefixes,omitempty" yaml:"family_prefixes"`
	CanonicalPrefixes []string `json:"canonical_prefixes,omitempty" yaml:"canonical_prefixes"`
}

type ManifestModelDiscovery struct {
	Path             string            `json:"path,omitempty" yaml:"path"`
	Auth             string            `json:"auth,omitempty" yaml:"auth"`
	APIKeyQueryParam string            `json:"api_key_query_param,omitempty" yaml:"api_key_query_param"`
	Headers          map[string]string `json:"headers,omitempty" yaml:"headers"`
}

type ManifestNetworkPermissions struct {
	Allow []string `yaml:"allow"`
}

type ManifestPermissions struct {
	Network ManifestNetworkPermissions `yaml:"network"`
	Data    ManifestDataPermissions    `yaml:"data"`
}

type ManifestProvider struct {
	RouteProtocols                   []string                `yaml:"route_protocols"`
	AuthModes                        []string                `yaml:"auth_modes"`
	AuthModeLegacyOption             string                  `yaml:"auth_mode_legacy_option"`
	AuthModeInvalidErrorCode         string                  `yaml:"auth_mode_invalid_error_code"`
	AuthModeInvalidErrorMessage      string                  `yaml:"auth_mode_invalid_error_message"`
	SupportsCustomHeaders            *bool                   `yaml:"supports_custom_headers"`
	ManagedHeaders                   []string                `yaml:"managed_headers"`
	APIKeyRequired                   *bool                   `yaml:"api_key_required"`
	RouteRequiresResource            *bool                   `yaml:"route_requires_resource"`
	StoreProbeFallback               *bool                   `yaml:"store_probe_fallback"`
	CredentialsScope                 string                  `yaml:"credentials_scope"`
	SessionAffinityKind              string                  `yaml:"session_affinity_kind"`
	SessionAffinityIdentifierProfile string                  `yaml:"session_affinity_identifier_profile"`
	SystemPromptTransformDefault     string                  `yaml:"system_prompt_transform_default"`
	ClaudeCodeAttributionDefault     string                  `yaml:"claude_code_attribution_default"`
	ReasoningConfigurable            *bool                   `yaml:"reasoning_configurable"`
	PreserveReasoningContent         *bool                   `yaml:"preserve_reasoning_content"`
	ResponsesModelAllowlist          []string                `yaml:"responses_model_allowlist"`
	DefaultBaseURL                   string                  `yaml:"default_base_url"`
	DefaultCatalogProviderType       bool                    `yaml:"default_catalog_provider_type"`
	ErrorProfile                     string                  `yaml:"error_profile"`
	ModelDiscovery                   ManifestModelDiscovery  `yaml:"model_discovery"`
	ModelCategories                  []ManifestModelCategory `yaml:"model_categories"`
	Catalog                          ManifestProviderCatalog `yaml:"catalog"`
}

type ManifestProviderCatalog struct {
	ID                                string                         `json:"id,omitempty" yaml:"id"`
	Name                              string                         `json:"name,omitempty" yaml:"name"`
	DisplayName                       string                         `json:"display_name,omitempty" yaml:"display_name"`
	Type                              string                         `json:"type,omitempty" yaml:"type"`
	BaseURL                           string                         `json:"base_url,omitempty" yaml:"base_url"`
	DocURL                            string                         `json:"doc_url,omitempty" yaml:"doc_url"`
	Categories                        []string                       `json:"categories,omitempty" yaml:"categories"`
	ModelsCount                       int                            `json:"models_count,omitempty" yaml:"models_count"`
	Models                            []ManifestProviderCatalogModel `json:"models,omitempty" yaml:"models"`
	ETag                              string                         `json:"etag,omitempty" yaml:"etag"`
	ModelsAccountRequiredErrorCode    string                         `json:"models_account_required_error_code,omitempty" yaml:"models_account_required_error_code"`
	ModelsAccountRequiredErrorMessage string                         `json:"models_account_required_error_message,omitempty" yaml:"models_account_required_error_message"`
}

type ManifestProviderCatalogModel struct {
	ID                        string            `json:"id" yaml:"id"`
	Name                      string            `json:"name,omitempty" yaml:"name"`
	DisplayName               string            `json:"display_name,omitempty" yaml:"display_name"`
	CanonicalName             string            `json:"canonical_name,omitempty" yaml:"canonical_name"`
	Category                  string            `json:"category,omitempty" yaml:"category"`
	Family                    string            `json:"family,omitempty" yaml:"family"`
	Type                      string            `json:"type,omitempty" yaml:"type"`
	ContextWindow             int64             `json:"context_window,omitempty" yaml:"context_window"`
	MaxOutputTokens           int64             `json:"max_output_tokens,omitempty" yaml:"max_output_tokens"`
	InputPriceUSDPer1M        float64           `json:"input_price_usd_per_1m,omitempty" yaml:"input_price_usd_per_1m"`
	CacheReadPriceUSDPer1M    float64           `json:"cache_read_price_usd_per_1m,omitempty" yaml:"cache_read_price_usd_per_1m"`
	CacheWritePriceUSDPer1M   float64           `json:"cache_write_price_usd_per_1m,omitempty" yaml:"cache_write_price_usd_per_1m"`
	CacheWrite5mPriceUSDPer1M float64           `json:"cache_write_5m_price_usd_per_1m,omitempty" yaml:"cache_write_5m_price_usd_per_1m"`
	CacheWrite1hPriceUSDPer1M float64           `json:"cache_write_1h_price_usd_per_1m,omitempty" yaml:"cache_write_1h_price_usd_per_1m"`
	OutputPriceUSDPer1M       float64           `json:"output_price_usd_per_1m,omitempty" yaml:"output_price_usd_per_1m"`
	InputModalities           []string          `json:"input_modalities,omitempty" yaml:"input_modalities"`
	OutputModalities          []string          `json:"output_modalities,omitempty" yaml:"output_modalities"`
	Capabilities              []string          `json:"capabilities,omitempty" yaml:"capabilities"`
	SupportedParameters       []string          `json:"supported_parameters,omitempty" yaml:"supported_parameters"`
	LastUpdated               string            `json:"last_updated,omitempty" yaml:"last_updated"`
	Metadata                  map[string]string `json:"metadata,omitempty" yaml:"metadata"`
}

type ManifestProviderResourceType struct {
	Type                      string            `json:"type" yaml:"type"`
	DisplayName               string            `json:"display_name,omitempty" yaml:"display_name"`
	AuthModes                 []string          `json:"auth_modes,omitempty" yaml:"auth_modes"`
	Defaults                  map[string]string `json:"defaults,omitempty" yaml:"defaults"`
	CredentialIdentityProfile string            `json:"credential_identity_profile,omitempty" yaml:"credential_identity_profile"`
	CredentialInputOptional   bool              `json:"credential_input_optional,omitempty" yaml:"credential_input_optional"`
	Default                   bool              `json:"default,omitempty" yaml:"default"`
}

type ManifestSIM struct {
	ThemeTokens           []ManifestSIMThemeTokens          `yaml:"theme_tokens"`
	ShellLayouts          []ManifestSIMShellLayout          `yaml:"shell_layouts"`
	PageTemplates         []ManifestSIMPageTemplate         `yaml:"page_templates"`
	DashboardCompositions []ManifestSIMDashboardComposition `yaml:"dashboard_compositions"`
}

type ManifestSIMDashboardCardSlot struct {
	ContributionID string `json:"contribution_id" yaml:"contribution_id"`
	Region         string `json:"region,omitempty" yaml:"region"`
	Size           string `json:"size,omitempty" yaml:"size"`
	Order          int    `json:"order,omitempty" yaml:"order"`
}

type ManifestSIMDashboardComposition struct {
	ID      string                         `json:"id" yaml:"id"`
	Layout  string                         `json:"layout,omitempty" yaml:"layout"`
	Cards   []ManifestSIMDashboardCardSlot `json:"cards,omitempty" yaml:"cards"`
	Default bool                           `json:"default,omitempty" yaml:"default"`
}

type ManifestSIMPageTemplate struct {
	ID      string   `json:"id" yaml:"id"`
	Target  string   `json:"target" yaml:"target"`
	Layout  string   `json:"layout,omitempty" yaml:"layout"`
	Regions []string `json:"regions,omitempty" yaml:"regions"`
	Default bool     `json:"default,omitempty" yaml:"default"`
}

type ManifestSIMShellLayout struct {
	ID           string `json:"id" yaml:"id"`
	Navigation   string `json:"navigation,omitempty" yaml:"navigation"`
	Density      string `json:"density,omitempty" yaml:"density"`
	ContentWidth string `json:"content_width,omitempty" yaml:"content_width"`
	Default      bool   `json:"default,omitempty" yaml:"default"`
}

type ManifestSIMThemeTokens struct {
	ID      string            `json:"id" yaml:"id"`
	Mode    string            `json:"mode,omitempty" yaml:"mode"`
	Default bool              `json:"default,omitempty" yaml:"default"`
	Tokens  map[string]string `json:"tokens,omitempty" yaml:"tokens"`
}

type ManifestSettings struct {
	Scopes []string `json:"scopes,omitempty" yaml:"scopes"`
}

type MarketplaceAdvisory struct {
	ID          string `json:"id,omitempty" yaml:"id"`
	Severity    string `json:"severity,omitempty" yaml:"severity"`
	Title       string `json:"title,omitempty" yaml:"title"`
	URL         string `json:"url,omitempty" yaml:"url"`
	PublishedAt string `json:"published_at,omitempty" yaml:"published_at"`
	UpdatedAt   string `json:"updated_at,omitempty" yaml:"updated_at"`
}

type MarketplaceCompatibility struct {
	Verdict MarketplaceCompatibilityVerdict `json:"verdict,omitempty" yaml:"verdict"`
	Badges  []MarketplaceCompatibilityBadge `json:"badges,omitempty" yaml:"badges"`
}

type MarketplaceCompatibilityBadge struct {
	ID    string `json:"id,omitempty" yaml:"id"`
	Label string `json:"label,omitempty" yaml:"label"`
	Tone  string `json:"tone,omitempty" yaml:"tone"`
	URL   string `json:"url,omitempty" yaml:"url"`
}

type MarketplaceCompatibilityVerdict = string

type MarketplaceLocalization struct {
	Name         string `json:"name,omitempty" yaml:"name"`
	Summary      string `json:"summary,omitempty" yaml:"summary"`
	Description  string `json:"description,omitempty" yaml:"description"`
	ReleaseNotes string `json:"release_notes,omitempty" yaml:"release_notes"`
}

type MarketplaceMetadata struct {
	Summary       string                             `json:"summary,omitempty" yaml:"summary"`
	Categories    []string                           `json:"categories,omitempty" yaml:"categories"`
	Screenshots   []MarketplaceScreenshot            `json:"screenshots,omitempty" yaml:"screenshots"`
	Localizations map[string]MarketplaceLocalization `json:"localizations,omitempty" yaml:"localizations"`
	Compatibility *MarketplaceCompatibility          `json:"compatibility,omitempty" yaml:"compatibility"`
	Publisher     *MarketplacePublisher              `json:"publisher,omitempty" yaml:"publisher"`
	Advisories    []MarketplaceAdvisory              `json:"advisories,omitempty" yaml:"advisories"`
	ReleaseNotes  []MarketplaceReleaseNote           `json:"release_notes,omitempty" yaml:"release_notes"`
}

type MarketplacePublisher struct {
	ID         string `json:"id,omitempty" yaml:"id"`
	Name       string `json:"name,omitempty" yaml:"name"`
	URL        string `json:"url,omitempty" yaml:"url"`
	SupportURL string `json:"support_url,omitempty" yaml:"support_url"`
	ContactURL string `json:"contact_url,omitempty" yaml:"contact_url"`
	Verified   bool   `json:"verified,omitempty" yaml:"verified"`
}

type MarketplaceReleaseNote struct {
	Version string   `json:"version,omitempty" yaml:"version"`
	Date    string   `json:"date,omitempty" yaml:"date"`
	Title   string   `json:"title,omitempty" yaml:"title"`
	Notes   string   `json:"notes,omitempty" yaml:"notes"`
	URL     string   `json:"url,omitempty" yaml:"url"`
	Items   []string `json:"items,omitempty" yaml:"items"`
}

type MarketplaceScreenshot struct {
	URL          string `json:"url,omitempty" yaml:"url"`
	ThumbnailURL string `json:"thumbnail_url,omitempty" yaml:"thumbnail_url"`
	Alt          string `json:"alt,omitempty" yaml:"alt"`
	Caption      string `json:"caption,omitempty" yaml:"caption"`
	Locale       string `json:"locale,omitempty" yaml:"locale"`
	Width        int    `json:"width,omitempty" yaml:"width"`
	Height       int    `json:"height,omitempty" yaml:"height"`
}

type Placement = string
